###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: yii2-shortener-memcached

    mariadb:
      image: mariadb:10.1
      container_name: yii2-shortener-mariadb
      working_dir: /application
      volumes:
        - dbshortener:/var/lib/mysql
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=shortener
        - MYSQL_USER=dev
        - MYSQL_PASSWORD=dev
      ports:
        - "8084:3306"

    webserver:
      image: nginx:alpine
      container_name: yii2-shortener-webserver
      working_dir: /application
      links:
        - php-fpm
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8081:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: yii2-shortener-php-fpm
      working_dir: /application
      environment:
        PHP_IDE_CONFIG: "serverName=yii2_shortener"
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
        - ./phpdocker/php-fpm/xdebug.ini:/etc/php/7.2/fpm/conf.d/99-xdebug.ini
volumes:
  dbshortener:
